### ISSUE TITLE
unsupported SEXPTYPE: 19

### ISSUE THREAD

**Issue by lawremi** [alexcb/rjson#13] opened 2018-05-17 22:20 UTC
This case below causes the above message to be printed:

```
{
    "array":[
	{
	    "foo":"bar"
	},
	{
	    "bah":"baz"
	},
    ]
}
```

It also fails to load the contents of the "array" object:
```
$array
list()
```

Btw, I'd recommend making that printed message an error.

**Comment by alexcb** [comment] 2018-05-18 16:58
thanks for the report, I can reproduce it.

```
> fromJSON('{ "array":[ { "foo":"bar" }, { "bah":"baz" }, ] }')
unsupported SEXPTYPE: 19
unsupported SEXPTYPE: 19
Warning: stack imbalance in '.Call', 12 then 14
Warning: stack imbalance in '[[', 10 then 12
Warning: stack imbalance in '<-', 8 then 10
$array
list()
```

technically that should be rejected due to the trailing comma; however, the issue is also present without the trailing comma:

```
> fromJSON('{ "array":[ { "foo":"bar" }, { "bah":"baz" }] }')
unsupported SEXPTYPE: 19
unsupported SEXPTYPE: 19
$array
$array[[1]]
NULL

$array[[2]]
NULL
```

**Comment by alexcb** [comment] 2018-05-18 17:03
the bug exists in the simplification logic:
```
fromJSON('{ "array":[ { "foo":"bar" }, { "bah":"baz" }] }', simplify=FALSE)
$array
$array[[1]]
$array[[1]]$foo
[1] "bar"


$array[[2]]
$array[[2]]$bah
[1] "baz"
``` works

however no error is raised for 
```> fromJSON('{ "array":[ { "foo":"bar" }, { "bah":"baz" },] }', simplify=FALSE)
Warning: stack imbalance in '.Call', 12 then 14
Warning: stack imbalance in '[[', 10 then 12
Warning: stack imbalance in '<-', 8 then 10
$array
list()
```

**Comment by alexcb** [comment] 2018-05-18 17:12
fixed in 257352c

**Comment by lawremi** [comment] 2018-05-18 17:20
Great, thanks for the quick turnaround. If you could please get it up on CRAN at some point, it would get my rsolr package building again.

**Comment by alexcb** [comment] 2018-05-18 17:26
just submitted it under 0.2.19, lets hope it gets accepted :)

**Comment by alexcb** [comment] 2018-05-22 21:03
Looks like it's up on CRAN now.
```
> install.packages('rjson')
Installing package into ‘/home/alex/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cloud.r-project.org/src/contrib/rjson_0.2.19.tar.gz'
Content type 'application/x-gzip' length 99520 bytes (97 KB)

> library(rjson)
> fromJSON('{ "array":[ { "foo":"bar" }, { "bah":"baz" }, ] }')
Error in fromJSON("{ \"array\":[ { \"foo\":\"bar\" }, { \"bah\":\"baz\" }, ] }") : 
  trailing comma found in array
> fromJSON('{ "array":[ { "foo":"bar" }, { "bah":"baz" }] }')
$array
$array[[1]]
$array[[1]]$foo
[1] "bar"


$array[[2]]
$array[[2]]$bah
[1] "baz"
```

Cheers

**Closed by alexcb** 2018-05-22 21:03 UTC
